### PR TITLE
Fix the link in the README

### PR DESCRIPTION
**Pull request by rolandinsh**
Fixing  ICD-10-CSV Github repo link

### CODE REVIEW

**Review by senorbacon — CHANGES_REQUESTED** [review]
Thanks for your PR!  Can you use https instead of http?

**Comment by rolandinsh** [comment]
changed http to https :)

**Review by senorbacon — APPROVED** [review]
Thanks again!  How did you find this repo may I ask?

**Comment by rolandinsh** [comment]
I guess it was featured on @neo4j website "This Week In Neo4j" via  https://www.slideshare.net/neo4j/this-week-in-neo4j-23rd-june-2018 -> https://neo4j.com/blog/this-week-in-neo4j-world-cup-graph-and-graphql-api-tuning-cypher-queries-querying-spatial-datapoints/#projects-knowledge-mortality-rdf-graph

**Comment by senorbacon** [comment]
Ah! Very cool. Still have a long way to go with the API / front end but the graph is there.

**Pull request merged**
